# action.yml
name: 'Helm GCP Push'
description: 'Pushes a local chart to a GCP OCI compatible registry' 
branding:
  color: 'green'
  icon: 'upload-cloud'
inputs:
  username:
    description: 'Username read/write permissions to the helm registry'
    required: false
    default: 'oauth2accesstoken'
  registry-url:
    description: 'Repository url'
    required: true
    default: ''
  chart-folder:
    description: 'Relative path to chart folder'
    required: false
    default: 'chart'
  gcp-wip-docker:
    description: 'If publishing to big cloud registries, utilizing OCI container spec for helm packages, set to true'
    required: true
    default: 'true'
  gcp-access-token:
    description:
    required: false
    default: ''
  gcp-location:
    description: 'The chosen location determines where the repository storage is created. Default: us'
    required: false
    default: 'us'
  source-dir:
    description: 'The local directory you wish to upload'
    required: no
    default: '.'
    # valid list of args for `helm repo add $args` each line maps to repo add e.g.
    # add-repositories: |
    #     stable https://charts.helm.sh/stable
    #     private https//private.internal --username private --password 'bulls eye'
    #     ...
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHART_FOLDER: ${{ inputs.chart-folder }}
    REGISTRY_URL: ${{ inputs.registry-url }}
    REGISTRY_USERNAME: ${{ inputs.username }}
    REGISTRY_TOKEN: ${{ inputs.token }}
    GCP_WIP_DOCKER: ${{ inputs.gcp-wip }}
    GCP_ACCESS_TOKEN: ${{ intputs.gcp-access-token }}
    GCP_LOCATION: ${{ inputs.gcp-location }}
    SOURCE_DIR: ${{ inputs.source-dir }}

